# stubs/mqtt_pipeline/__init__.pyi

class Pipeline:
    def __init__(self, config: dict = None, logger = None) -> None: ...
    def add_middleware(self, middleware_class): ...
    def build_middleware_stack(self): ...
    def process_core(self, data, *args, **kwargs): ...
    def process(self, data, *args, **kwargs): ...

class Middleware:
    def __init__(self, get_response, config=None, logger=None): ...
    def __call__(self, request, *args, **kwargs): ...
